In [1]:
import numpy as np

In [17]:
#Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением
a=np.array([1,2,3,4,5])
b=np.zeros(len(a)+(len(a)-1)*3)
b[::4]=a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [37]:
#Поменять 2 строки в матрице
a=np.random.randint(0,100,size=(5,3))
print(a)
a[[0,1]]=a[[1,0]]
print(a)

[[71 51 24]
 [61 85 32]
 [42 93 96]
 [38  5 65]
 [67 11 31]]
[[61 85 32]
 [71 51 24]
 [42 93 96]
 [38  5 65]
 [67 11 31]]


In [2]:
#Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники
faces = np.random.randint(0,100,(10,3))
a = np.roll(faces.repeat(2,axis=1),-1,axis=1)
a = a.reshape(len(a)*3,2)
a = np.sort(a,axis=1)
b = a.view( dtype=[('p0',a.dtype),('p1',a.dtype)] )
b = np.unique(b)
print(b)

[( 0,  5) ( 0, 18) ( 3, 27) ( 3, 48) ( 5, 18) ( 5, 39) ( 5, 77) ( 8, 34)
 ( 8, 37) ( 8, 79) ( 8, 84) (12, 25) (12, 34) (21, 26) (21, 45) (25, 34)
 (26, 45) (27, 48) (34, 84) (37, 79) (38, 69) (38, 79) (39, 77) (39, 78)
 (39, 81) (54, 64) (54, 78) (64, 78) (69, 79) (78, 81)]


In [39]:
#Дан массив C; создать массив A, что np.bincount(A) == C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
np.bincount(A)==C

array([ True,  True,  True,  True,  True,  True,  True])

In [57]:
#Посчитать среднее, используя плавающее окно
def moving_average(a, n=3):
    ret = np.cumsum(a)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
b = np.arange(10)
print(b)
print(moving_average(b, 3))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]
[1. 2. 3. 4. 5. 6. 7. 8.]


In [3]:
#Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
b = rolling(np.arange(10), 3)
print(b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [48]:
#Инвертировать булево значение, или поменять знак у числового массива без создания нового
a=np.random.randint(0,5,size=(1,5))
print(a)
print(np.negative(a))

[[2 3 0 3 2]]
[[-2 -3  0 -3 -2]]


In [7]:
#Рассмотрим 2 набора точек P0, P1 описания линии (2D) и точку р, как вычислить расстояние от р до каждой линии i (P0[i],P1[i])
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[14.96978088 11.08388047  8.36081544  2.44233026 16.86244189  5.87287039
  1.40536308  0.21032294  0.13067488  1.01052368]


In [40]:
#Дан массив. Написать функцию, выделяющую часть массива фиксированного размера с центром в данном элементе (дополненное значением fill если необходимо)
Z = np.random.randint(0,10, (10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P - Rs//2)
Z_stop  = (P + Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 6 7 2 9 1 0 8 8 9]
 [5 2 7 0 2 9 0 7 5 9]
 [9 4 9 4 9 9 9 2 0 6]
 [7 1 6 5 6 7 2 8 7 2]
 [1 7 6 5 8 0 2 8 4 8]
 [5 9 4 9 2 0 7 2 9 0]
 [9 5 1 0 8 7 9 3 5 0]
 [9 1 1 6 1 6 7 2 5 5]
 [3 0 3 8 3 8 6 2 3 1]
 [2 0 9 1 7 5 0 4 9 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[6 6 7 2 9 1 0 8 8 9]
 [5 2 7 0 2 9 0 7 5 9]
 [9 4 9 4 9 9 9 2 0 6]
 [7 1 6 5 6 7 2 8 7 2]
 [1 7 6 5 8 0 2 8 4 8]
 [5 9 4 9 2 0 7 2 9 0]
 [9 5 1 0 8 7 9 3 5 0]
 [9 1 1 6 1 6 7 2 5 5]
 [3 0 3 8 3 8 6 2 3 1]
 [2 0 9 1 7 5 0 4 9 0]]
[[0 0 0 0 0]
 [0 6 6 7 2]
 [0 5 2 7 0]
 [0 9 4 9 4]
 [0 7 1 6 5]]


C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [45]:
#Посчитать ранг матрицы
a=np.random.randint(0,10,size=(3,3))
print(a)
print(np.linalg.matrix_rank(a))

[[7 8 4]
 [2 8 6]
 [6 7 2]]
3


In [46]:
#Найти наиболее частое значение в массиве
a=np.random.randint(0,10,7)
print(a)
print(np.bincount(a).argmax())

[8 8 8 3 0 9 6]
8


In [14]:
#Извлечь все смежные 3x3 блоки из 10x10 матрицы
a = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (a.shape[0] - n)
j = 1 + (a.shape[1] - n)
b = stride_tricks.as_strided(a, shape=(i, j, n, n), strides=a.strides + a.strides)
print(a)
print(b)

[[0 1 2 4 3 0 2 1 3 3]
 [1 3 4 3 0 0 4 3 1 0]
 [1 2 1 4 0 1 0 4 1 3]
 [0 2 3 0 3 3 2 2 4 1]
 [2 1 3 3 2 4 4 4 2 1]
 [3 0 3 4 3 4 0 0 2 1]
 [2 1 1 0 4 0 2 0 0 1]
 [3 2 1 1 0 3 1 2 4 1]
 [0 4 0 4 0 3 0 4 2 4]
 [3 1 1 3 3 3 4 3 2 2]]
[[[[0 1 2]
   [1 3 4]
   [1 2 1]]

  [[1 2 4]
   [3 4 3]
   [2 1 4]]

  [[2 4 3]
   [4 3 0]
   [1 4 0]]

  [[4 3 0]
   [3 0 0]
   [4 0 1]]

  [[3 0 2]
   [0 0 4]
   [0 1 0]]

  [[0 2 1]
   [0 4 3]
   [1 0 4]]

  [[2 1 3]
   [4 3 1]
   [0 4 1]]

  [[1 3 3]
   [3 1 0]
   [4 1 3]]]


 [[[1 3 4]
   [1 2 1]
   [0 2 3]]

  [[3 4 3]
   [2 1 4]
   [2 3 0]]

  [[4 3 0]
   [1 4 0]
   [3 0 3]]

  [[3 0 0]
   [4 0 1]
   [0 3 3]]

  [[0 0 4]
   [0 1 0]
   [3 3 2]]

  [[0 4 3]
   [1 0 4]
   [3 2 2]]

  [[4 3 1]
   [0 4 1]
   [2 2 4]]

  [[3 1 0]
   [4 1 3]
   [2 4 1]]]


 [[[1 2 1]
   [0 2 3]
   [2 1 3]]

  [[2 1 4]
   [2 3 0]
   [1 3 3]]

  [[1 4 0]
   [3 0 3]
   [3 3 2]]

  [[4 0 1]
   [0 3 3]
   [3 2 4]]

  [[0 1 0]
   [3 3 2]
   [2 4 4]]

  [[1 0 4]
   [3 2 2]
   [4 4 

In [ ]:
#Создать подкласс симметричных 2D массивов (Z[i,j] == Z[j,i])
class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

In [20]:
#Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))
p, n = 4, 6
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[24.]
 [24.]
 [24.]
 [24.]
 [24.]
 [24.]]


In [24]:
#Дан массив 16x16, посчитать сумму по блокам 4x4
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [28]:
#Найти n наибольших значений в массиве
a = np.arange(10)
np.random.shuffle(a)
n = 5
print(a)
print (a[np.argpartition(-a,n)[:n]])

[7 8 1 5 6 4 2 3 9 0]
[8 7 9 6 5]


In [29]:
#Построить прямое произведение массивов (все комбинации с каждым элементом)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [35]:
#Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B
A = np.random.randint(0,6,(8,3))
B = np.random.randint(0,2,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(A)
print(B)
print(C)
print(rows)

[[2 2 4]
 [0 2 2]
 [1 2 4]
 [5 4 0]
 [5 3 3]
 [4 2 4]
 [0 4 3]
 [0 0 0]]
[[0 1]
 [1 0]]
[[[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[ True False]
   [False  True]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False  True]
   [ True False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[ True False]
   [False  True]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[ True False]
   [False  True]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[ True False]
   [False  True]]

  [[ True False]
   [False  True]]

  [[ True False]
   [False  True]]]]
[1 2 3 6 7]


In [36]:
#Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])
a=np.random.randint(0,2,size=(10,3))
b = np.logical_and.reduce(a[:,1:] == a[:,:-1], axis=1)
c = a[~b]
print(a)
print(b)
print(c)

[[1 0 1]
 [1 0 0]
 [1 1 0]
 [0 0 0]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [1 0 0]]
[False False False  True False False False False False False]
[[1 0 1]
 [1 0 0]
 [1 1 0]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [1 0 0]]


In [30]:
#Преобразовать вектор чисел в матрицу бинарных представлений
a = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(a)
print(np.unpackbits(a[:, np.newaxis], axis=1))

[  0   1   2   3  15  16  32  64 128]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [38]:
#Дан двумерный массив. Найти все различные строки
a = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(a).view(np.dtype((np.void, a.dtype.itemsize * a.shape[1])))
_, idx = np.unique(T, return_index=True)
ua = a[idx]
print(a)
print(T)
print(_)
print(idx)
print(ua)

[[1 1 0]
 [0 1 0]
 [1 1 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]]
[[b'\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00']
 [b'\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00']
 [b'\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00']
 [b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
 [b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00']
 [b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00']]
[b'\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00'
 b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
 b'\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00'
 b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00']
[1 3 0 4]
[[0 1 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


In [18]:
#Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul
A=np.array([1,2,3,4,5])
B=np.array([10,20,30,40,55])
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)

array([[ 10,  20,  30,  40,  55],
       [ 20,  40,  60,  80, 110],
       [ 30,  60,  90, 120, 165],
       [ 40,  80, 120, 160, 220],
       [ 50, 100, 150, 200, 275]])