In [10]:
import numpy as np

In [17]:
#Перемножить матрицы 5x3 и 3x2
a=np.random.randint(0,100,size=(5,3))
b=np.random.randint(0,100,size=(3,2))
print(np.dot(a,b))

[[ 5470 12200]
 [ 8445 12002]
 [ 2701  9774]
 [ 7921  8978]
 [ 8479 17510]]


In [34]:
#Дан массив, поменять знак у элементов, значения которых между 3 и 8
a= np.arange(10)
a[(3 < a) & (a <=8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [40]:
#Создать 5x5 матрицу со значениями в строках от 0 до 4
np.tile(np.array([[0,1,2,3,4]]),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [7]:
#Есть генератор, сделать с его помощью массив
def generate():
    for x in np.arange(10):
        yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [8]:
#Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни друое
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [15]:
#Отсортировать вектор
np.sort(np.random.random(10))

array([0.07981416, 0.19880561, 0.31581927, 0.4210855 , 0.55465516,
       0.56329348, 0.63739302, 0.7963244 , 0.81051081, 0.88882363])

In [20]:
#Проверить, одинаковы ли 2 numpy массива
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(str(a)+'\n'+str(b))
np.allclose(a,b)

[1 0 0 1 1]
[1 0 0 1 0]


False

In [22]:
#Сделать массив неизменяемым
a = np.ones(10)
a.flags.writeable = False
a[0] = 2

ValueError: assignment destination is read-only

In [36]:
#Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную
a=np.random.randint(0,100,size=(2, 10))
x,y= a[:,0], a[:,1]
r = np.hypot(x,y)  #полярный радиус=sqrt(x^2+y^2)
t = np.arctan2(y,x) #tg(угол)=y/x
print(r)
print(t)

[69.85699679 93.0376268 ]
[0.41241044 0.44441921]


In [34]:
#Заменить максимальный элемент на ноль
a=np.random.randint(0,100,size=(1, 10))
print(a)
print(a.argmax())
a[0][a.argmax()]=0
print(a)

[[ 8 71  6 24 59 82 97 81 86 41]]
6
[[ 8 71  6 24 59 82  0 81 86 41]]


In [42]:
#Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10),sparse=True)
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [47]:
#Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c)) #определитель

3638.1636371179666


In [ ]:
#Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

In [50]:
#Напечатать все значения в массиве
np.random.randint(0,100,size=(2, 10))

array([[91, 72, 72,  1, 36, 99, 31, 94, 37, 58],
       [ 2,  4, 74, 11, 36, 53, 24, 41, 88, 48]])

In [52]:
#Найти ближайшее к заданному значению число в заданном массиве
a= np.arange(100)
b = np.random.uniform(0,100)
print(str(a)+'\n'+str(b))
i = (np.abs(a-b)).argmin()
print(a[i])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
16.251389529935334
16


In [54]:
#Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)
np.zeros(10, [ ('координата', [ ('x', float),
                                   ('y', float)]),
                    ('цвет',    [ ('r', float),
                                   ('g', float),
                                   ('b', float)])])

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('координата', [('x', '<f8'), ('y', '<f8')]), ('цвет', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [55]:
#Дан массив (100,2) координат, найти расстояние от каждой точки до каждой
from scipy.spatial.distance import cdist
a=np.random.random((10,2))
cdist(a,a)

array([[0.        , 0.1271877 , 0.74317947, 0.41475279, 0.73993252,
        0.39228089, 0.323131  , 0.1065269 , 0.17088069, 0.85231416],
       [0.1271877 , 0.        , 0.85448423, 0.47466506, 0.85377606,
        0.43738869, 0.44370672, 0.09684567, 0.21401882, 0.8429811 ],
       [0.74317947, 0.85448423, 0.        , 0.48960213, 0.03422015,
        0.55195574, 0.60688258, 0.84575324, 0.84324745, 0.88824812],
       [0.41475279, 0.47466506, 0.48960213, 0.        , 0.5049192 ,
        0.06255574, 0.53137914, 0.51537867, 0.57741833, 0.5297098 ],
       [0.73993252, 0.85377606, 0.03422015, 0.5049192 , 0.        ,
        0.56687478, 0.5894857 , 0.84117595, 0.83400183, 0.91664961],
       [0.39228089, 0.43738869, 0.55195574, 0.06255574, 0.56687478,
        0.        , 0.54811996, 0.48764502, 0.56016922, 0.50511018],
       [0.323131  , 0.44370672, 0.60688258, 0.53137914, 0.5894857 ,
        0.54811996, 0.        , 0.37350674, 0.30246705, 1.0531693 ],
       [0.1065269 , 0.09684567, 0.8457532

In [63]:
#Преобразовать массив из float в int
np.arange(10, dtype=np.float32).astype(np.int32, copy=False)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
#Дан файл:
#1,2,3,4,5
#6,,,7,8
#,,9,10,11
#Как прочитать его?

np.genfromtxt("file.txt", delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

In [80]:
#Каков эквивалент функции enumerate для numpy массивов?
a = np.arange(9)
for index, value in np.ndenumerate(a):
    print(index, value)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5
(6,) 6
(7,) 7
(8,) 8


In [83]:
#Сформировать 2D массив с распределением Гаусса
np.random.normal(0, 0.1,size=(2,3))

array([[-0.12410832,  0.05558701,  0.00642456],
       [ 0.10867617, -0.01040059,  0.01327613]])

In [86]:
#Случайно расположить p элементов в 2D массив
a = np.zeros((3,3))
print(a)
np.put(a, np.random.choice(range(3*3), 2, replace=False), 2)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 2. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


In [90]:
#Отнять среднее из каждой строки в матрице
x = np.random.randint(0,10,size=(1, 5))
y = x- x.mean(axis=1, keepdims=True)
print(x.mean(axis=1))
print(str(x)+'\n'+str(y))

[3.]
[[0 2 7 2 4]]
[[-3. -1.  4. -1.  1.]]


In [93]:
#Отсортировать матрицу по n-ому столбцу
a = np.random.randint(0,10,(3,3))
n = 2
print(a)
print(a[:,n].argsort())
print(a[a[:,n].argsort()])

[[9 3 6]
 [4 9 5]
 [7 9 8]]
[1 0 2]
[[4 9 5]
 [9 3 6]
 [7 9 8]]


In [98]:
#Определить, есть ли в 2D массиве нулевые столбцы
a = np.random.randint(0,3,(3,10))
print(a)
print((~a.any(axis=0)).any())

[[1 2 1 1 0 0 0 1 1 2]
 [2 1 0 2 1 2 2 0 0 2]
 [1 1 1 0 2 0 2 1 0 0]]
False


In [5]:
#Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)
a = np.ones(10)
i = np.random.randint(0,len(a),10)
print(i)
a += np.bincount(i, minlength=len(a))
print(a)

[4 1 8 9 3 6 6 1 0 1]
[2. 4. 1. 2. 2. 1. 3. 1. 2. 2.]


In [37]:
#Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов
w,h = 5,5
#I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
#F = I[...,0] * 256*256  + I[...,1] * 256 #+ I[...,2]
#n = len(np.unique(F))
a=np.random.randint(0,256,size=(w, h))
print(a)
print(len(np.unique(a)))

[[ 38  92 242 206 147]
 [ 19  39  50 251  41]
 [ 48 218 250  48 232]
 [222  24 138  98 168]
 [ 25 139 108  58  99]]
24


In [31]:
#Дан четырехмерный массив, посчитать сумму по последним двум осям
a = np.random.randint(0,10, (4,4,4,4))
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[87 73 81 59]
 [66 55 64 62]
 [83 79 61 58]
 [81 80 62 73]]


In [109]:
#Найти диагональные элементы произведения матриц
a=np.random.randint(0,10,size=(2, 2))
b=np.random.randint(0,10,size=(2, 2))
print(str(a)+'\n'+str(b))
np.sum(a * b.T, axis=1)

[[6 5]
 [6 0]]
[[5 7]
 [4 3]]


array([50, 42])