In [2]:
import numpy as np
print("Version NumPy is ",np.__version__)
print(np.show_config())

Version NumPy is  1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Admin/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\

In [33]:
#Создать вектор (одномерный массив) размера 10, заполненный нулями
#Создать вектор размера 10, заполненный единицами
#Создать вектор размера 10, заполненный числом 2.5

print(np.zeros((1, 10)))
print(np.ones((1,10)))
print(np.linspace(2.5,2.5,10))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [36]:
np.add.__doc__

"add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])\n\nAdd arguments element-wise.\n\nParameters\n----------\nx1, x2 : array_like\n    The arrays to be added.  If ``x1.shape != x2.shape``, they must be\n    broadcastable to a common shape (which may be the shape of one or\n    the other).\nout : ndarray, None, or tuple of ndarray and None, optional\n    A location into which the result is stored. If provided, it must have\n    a shape that the inputs broadcast to. If not provided or `None`,\n    a freshly-allocated array is returned. A tuple (possible only as a\n    keyword argument) must have length equal to the number of outputs.\nwhere : array_like, optional\n    Values of True indicate to calculate the ufunc at that position, values\n    of False indicate to leave the value in the output alone.\n**kwargs\n    For other keyword-only arguments, see the\n    :ref:`ufunc docs <ufuncs.kwargs>`.\n\nReturns\n-------\nadd : 

In [114]:
#Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1
a=np.zeros((1, 10))
a[0:,4:-5]=1
print(a)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [82]:
#Создать вектор со значениями от 10 до 49
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [50]:
#Развернуть вектор (первый становится последним
a=np.array([0,2,1,5,8,6,9,3])
print(a[len(a)::-1])

[3 9 6 8 5 1 2 0]


In [57]:
#Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8
def f1(i, j):
    return 3 * i + j

np.fromfunction(f1, (3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [116]:
#Найти индексы ненулевых элементов в [1,2,0,0,4,0]
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


In [5]:
#Создать массив 3x3x3? со случайными значениями
np.random.random((3,3,3))

array([[[0.05085516, 0.76093615, 0.43029472],
        [0.65844049, 0.62910295, 0.29758581],
        [0.05922393, 0.80314129, 0.46311123]],

       [[0.88660992, 0.41170638, 0.51667625],
        [0.39521872, 0.25892987, 0.70970537],
        [0.41988692, 0.50192997, 0.55852052]],

       [[0.34852476, 0.36833998, 0.35331237],
        [0.47453142, 0.8978085 , 0.86792579],
        [0.62960914, 0.68168072, 0.14495721]]])

In [124]:
#Создать массив 10x10 со случайными значениями, найти минимум и максимум
a=np.random.randint(0,5000,size=(10, 10))
print(a)
print(a.max())
print(a.min())

[[2857 2359 3156  888 2895 1137 3763 2498 2937  286]
 [1926 2949 3273 4958 1063 4104 1194   21 2298  458]
 [1630  639  948 2657 2097 4028 1490  545  780 4709]
 [ 325  287 2884 2045 2453 4168 2937 2944 3741  851]
 [3864  475 1357 4261 4851 1795 4925 4637 2408 4070]
 [1795 4284 4730 2798  330  782 1304 4313 2448 1130]
 [  16 2959 1263 3706  891  270 4744 2159  656  240]
 [ 608 2305 2674 3230 1198 3068 2435 4687 3788  911]
 [1559 3398  210  594 1630 2754 2769  760 2414 4849]
 [2536 1213   16 1744  402 4773 4181 2650 4385 3648]]
4958
16


In [126]:
#Создать случайный вектор размера 30 и найти среднее значение всех элементов
a=np.random.randint(0,100,size=(1, 30))
print(a)
print(a.mean())

[[91 25 75 37 77 83 89 58 62 27 94 34  2 25  3 30 24 47 73 36 42 48 18 80
  46 81 24 60  1 51]]
48.1


In [7]:
#Создать матрицу с 0 внутри, и 1 на границах
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
#Выяснить результат следующих выражений?
#(	0 * np.nan
#	np.nan == np.nan
#	np.inf > np.nan
#	np.nan - np.nan)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


In [132]:
#Создать 5x5 матрицу с 1,2,3,4 под диагональю
np.diag(np.arange(1, 5), k=-1) #Как вариант

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [133]:
#Создать 8x8 матрицу и заполнить её в шахматном порядке
a=np.zeros((8,8), dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
#Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [4]:
#Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])